### ISSUE TITLE
using Aggregation without window 

### ISSUE THREAD

**Issue by jafarrasooli** [CeZL/node-red-contrib-cep#1]
I want to use aggregate node without  time window. for example i have a message like  : 
```
{
    "eventName": "sale",
    "id": "1",
    "order": "1000",
    "product": "shoe"
}
```
I want to aggregate events  with the same id (grouped by id) until sum of their order is less than 20000.
when their sum passes 20000  new event should trigger. 
actually here window is sum of 'order' property and id. when ever the sum of order passes 20000 new event trigger and new window begin for next events.

**Comment by carloszimm** [comment]
Hi, @jafarrasooli!
Currently there are two types of windows available as you have seen. They are mainly used to limit the quantity of items that operations like sum, avg, var, should be working with. That being said, the way that you are willing to do is not possible, at least right now. However, what you can do is create a new node in your flow at the output of the aggregate node, like the function node, with two outputs, one output in case the new event generated is bellow 20000 and the other if the otherwise. If the first case happens, you'll probably need only to do a few tweaks on the event generated in case it does not have the source's fields/properties like eventType (pay attention that you are probably using an outdated version, so the eventType in your case is the same as eventName), hence it can be refeed back to the aggregate node much like any other event that is entering the node. In the aggregate node, you can keep your current setting, either using time window or count window (though time I think would be more suitable) and still grouping all events by id

**Comment by jafarrasooli** [comment]
thanks @CeZL. that is a good solution to the  problem. I think I should think more CEP way.
